server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuxiaofeng88/microservicecloud-config.git
          username: wuxiaofeng88
          password: wwlw911113