server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/znyy
      username: root
      password: 123
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
info:
  app.name: km.microcloud
  company.name: km
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #隐藏单个服务
  ignored-services: microservicecloud-dept
  #隐藏所有微服务
  #ignored-services: "*"
  #为服务添加前缀，即，原先的url访问地址为：http://myzuul.com:9527/mydept/dept/list ，添加前缀之后的访问地址为：http://myzuul.com:9527/km/mydept/dept/list
  prefix: /km